imshrunk	:	imshrunk.c ImageStuff.c ImageStuff.h
				gcc imshrunk.c ImageStuff.c -o imshrunk

sort		:	sort.c 
				gcc sort.c -o sort

imflipPM	:	imflipPM.c ImageStuff.c ImageStuff.h
				gcc imflipPM.c ImageStuff.c -o imflipPM -lpthread

imrotate	:	imrotate.c ImageStuff.c ImageStuff.h
				gcc imrotate.c ImageStuff.c -o imrotate -lpthread -lm

imrotateMC	:	imrotateMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMC.c ImageStuff.c -o imrotateMC -lpthread -lm

imedge		:	imedge.c ImageStuff.c ImageStuff.h
				gcc imedge.c ImageStuff.c -o imedge -lpthread -lm
				
imedgeMC	:	imedgeMC.c ImageStuff.c ImageStuff.h
				gcc imedgeMC.c ImageStuff.c -o imedgeMC -lpthread -lm
				
imedgeMCT	:	imedgeMCT.c ImageStuff.c ImageStuff.h
				gcc imedgeMCT.c ImageStuff.c -o imedgeMCT -lpthread -lm
